#!/bin/bash
intltool-extract --type=gettext/glade usr/share/hamonikr/pcchecker/pcchecker.glade

xml2po -o hamonikr-pcchecker.pot -m mallard usr/share/hamonikr/pcchecker/pcchecker.glade

xgettext --language=Python --keyword=_ --keyword=N_ --output=hamonikr-pcchecker.pot --join-existing usr/bin/*.py usr/share/hamonikr/pcchecker/*.glade.h

# msginit --input=hamonikr-lockdown.pot --locale=ko_KR -o po/hamonikr-lockdown-ko.po

rm -f gui/*.glade.h