#!/bin/bash
intltool-extract --type=gettext/glade debian/usr/share/hamonikr/pcchecker/pcchecker.glade

xml2po -o hamonikr-pcchecker.pot -m mallard debian/usr/share/hamonikr/pcchecker/pcchecker.glade

xgettext --language=Python --keyword=_ --keyword=N_ --output=hamonikr-pcchecker.pot --from-code=euc-ckr --join-existing debian/usr/bin/pcchecker.py debian/usr/share/hamonikr/pcchecker/pcchecker.glade.h

# msginit --input=hamonikr-lockdown.pot --locale=ko_KR -o po/hamonikr-lockdown-ko.po

rm -f debian/usr/share/hamonikr/pcchecker/*.glade.h